# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0006_auto_20170206_1337'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('link', '0002_auto_20160902_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='JmboLink',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('view_name', models.CharField(blank=True, help_text=b'View name to which this link will redirect.', max_length=256, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, help_text=b'URL to which this link will redirect.', max_length=256, null=True)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jmbo_link_target_content_type', to='contenttypes.ContentType')),
                ('view_params', models.ManyToManyField(blank=True, null=True, to='link.ViewParam')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Jmbo Link',
                'verbose_name_plural': 'Jmbo Links',
            },
            bases=('jmbo.modelbase',),
        ),
    ]
