# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link', '0002_auto_20160902_0249'),
        ('jmbo', '0007_auto_20170314_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('markdown', simplemde.fields.SimpleMDEField(blank=True, null=True)),
                ('django_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='link.Link')),
            ],
            bases=('jmbo.modelbase',),
        ),
    ]
